NuGet/ServerCommon

- build/sign.targets
- src/NuGet.Services.Configuration/NuGet.Services.Configuration.csproj
- src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
- src/NuGet.Services.Logging/NuGet.Services.Logging.csproj
- src/NuGet.Services.Logging/project.json
Depend on PR https://github.com/NuGet/ServerCommon/pull/22.
We will have our CI define `NUGET_SNK_PATH` environment variable.
> Add delay signing if NUGET_SNK_PATH is defined

- .gitignore
- build.ps1
- build/common.ps1
The goal here is to pull in a private repository which contains our .snk.
The repo is `PRIVATE_BUILD_TOOLS_REPO` and the commit is `PRIVATE_BUILD_TOOLS_COMMIT` (optional, defaulting to our current correct value).
> Add a step to get private build tools from another repository

- build.ps1
- buildandtest.ps1
We had pointless `param()`. Removed those too.
> Remove ReleaseLabel parameter and clean up build.ps1

- build/common.ps1
Merging one change:
*  Improve submodule support (#26)
> Merge 'develop' branch into 'master'

- NuGet.Server.Common.sln
- src/NuGet.Services.Logging/LoggingSetup.cs
- test.ps1
- tests/NuGet.Services.Logging.Tests/App.config
- tests/NuGet.Services.Logging.Tests/LoggingSetupTests.cs
- tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj
- tests/NuGet.Services.Logging.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Logging.Tests/project.json
> Fix duplicate event logging

- NuGet.Server.Common.sln
- src/NuGet.Services.Logging/LoggingSetup.cs
- test.ps1
- tests/NuGet.Services.Logging.Tests/App.config
- tests/NuGet.Services.Logging.Tests/LoggingSetupTests.cs
- tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj
- tests/NuGet.Services.Logging.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Logging.Tests/project.json
There was a hotfix on master so I needed to fix the merge conflicts before I could merge dev into master directly.
> Fix merge conflicts on dev

- .gitignore
- NuGet.Server.Common.sln
- build.ps1
- build/common.ps1
- src/NuGet.Services.Build/NuGet.Services.Build.csproj
- src/NuGet.Services.Build/Properties/AssemblyInfo.cs
- src/NuGet.Services.Build/VisualStudioSetupConfigurationHelper.cs
- src/NuGet.Services.Build/packages.config
(Second try, accidentally squashed the first time.)
> Fix merge conflicts

- build/common.ps1
includes "Fix MSBuild 15 finder script to work with machines with single instances of VS2017"
> Merge dev and master

- src/NuGet.Services.Storage/AggregateStorage.cs
- src/NuGet.Services.Storage/AggregateStorageFactory.cs
- src/NuGet.Services.Storage/AzureStorage.cs
- src/NuGet.Services.Storage/AzureStorageFactory.cs
- src/NuGet.Services.Storage/FileStorage.cs
- src/NuGet.Services.Storage/FileStorageFactory.cs
- src/NuGet.Services.Storage/Storage.cs
Code changes for the [#3889](https://github.com/NuGet/NuGetGallery/issues/3889)
> No more logger factories in Storage package

- NuGet.config
- src/NuGet.Services.Configuration/ConfigurationNullOrEmptyException.cs
- tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj
https://github.com/NuGet/NuGetGallery/issues/3818
> Add [Serializable] to ConfigurationNullOrEmptyException

- src/NuGet.Services.Logging/TelemetryResponseCodeProcessor.cs
- tests/NuGet.Services.Logging.Tests/TelemetryResponseCodeProcessorFacts.cs
Adds tweak to TelemetryResponseCodeProcessor  (#47)
> Merge develop into master

- NuGet.Server.Common.sln
- src/NuGet.Services.Contracts/ServiceBus/IBrokeredMessage.cs
- src/NuGet.Services.ServiceBus/BrokeredMessageWrapper.cs
- src/NuGet.Services.Validation/IPackageValidationEnqueuer.cs
- src/NuGet.Services.Validation/PackageValidationEnqueuer.cs
- tests/NuGet.Services.ServiceBus.Tests/BrokeredMessageWrapperFacts.cs
- tests/NuGet.Services.ServiceBus.Tests/NuGet.Services.ServiceBus.Tests.csproj
- tests/NuGet.Services.ServiceBus.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.ServiceBus.Tests/project.json
Needed for orchestrator to not process validation in tight-ish loop.
> Adding the ability to schedule validation message processing in the future

- src/NuGet.Services.Configuration/ConfigurationBuilderExtensions.cs
- src/NuGet.Services.Configuration/KeyVaultInjectingConfigurationProvider.cs
- src/NuGet.Services.Configuration/KeyVaultJsonInjectingConfigurationSource.cs
- src/NuGet.Services.Configuration/NonCachingOptionsSnapshot.cs
- src/NuGet.Services.Configuration/NuGet.Services.Configuration.csproj
- src/NuGet.Services.Configuration/project.json
- src/NuGet.Services.KeyVault/CachingSecretReaderFactory.cs
- src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
- tests/NuGet.Services.Configuration.Tests/KeyVaultInjectingConfigurationProviderFacts.cs
- tests/NuGet.Services.Configuration.Tests/MicrosoftExtensionsConfigurationIntegrationFacts.cs
- tests/NuGet.Services.Configuration.Tests/NuGet.Services.Configuration.Tests.csproj
- tests/NuGet.Services.Configuration.Tests/project.json
Retrying after accidental squash merge (#78)
> Merging Json Secret injection changes from dev to master

- src/NuGet.Services.Contracts/NuGet.Services.Contracts.csproj
- src/NuGet.Services.Contracts/Validation/IValidator.cs
- src/NuGet.Services.Contracts/Validation/ValidationResult.cs
- src/NuGet.Services.Validation/NuGet.Services.Validation.csproj
- src/NuGet.Services.Validation/ValidationResult.cs
- tests/NuGet.Services.Contracts.Tests/ContractsFacts.cs
This will be used by validators to report errors to the Gallery.
> Added ValidationResult to the contracts

- build/common.ps1
- src/NuGet.Services.Storage/AggregateStorage.cs
- src/NuGet.Services.Storage/AzureStorage.cs
- src/NuGet.Services.Storage/FileStorage.cs
- src/NuGet.Services.Storage/IStorage.cs
- src/NuGet.Services.Storage/Storage.cs
Patch release: version 2.5.1.
New APIs in `NuGet.Services.Storage`:
* `IStorage.Exists(string)`
* `IStorage.ExistsAsync(string, CancellationToken)`
> Merge dev to master

- tests/NuGet.Services.Cursor.Tests/DurableCursorFacts.cs
Yeay for reflection :)
@joelverhagen
> Fix test failure due to signature change of `Storage.OnSave` method

- tests/NuGet.Services.Cursor.Tests/DurableCursorFacts.cs
> Mock setup fixes

- NuGet.Server.Common.sln
- src/NuGet.Services.Cursor/DurableCursor.cs
- src/NuGet.Services.Storage/AggregateStorage.cs
- src/NuGet.Services.Storage/AzureStorage.cs
- src/NuGet.Services.Storage/FileStorage.cs
- src/NuGet.Services.Storage/IStorage.cs
- src/NuGet.Services.Storage/Storage.cs
- tests/NuGet.Services.Cursor.Tests/DurableCursorFacts.cs
- tests/NuGet.Services.Storage.Tests/AzureStorageFacts.cs
- tests/NuGet.Services.Storage.Tests/NuGet.Services.Storage.Tests.csproj
- tests/NuGet.Services.Storage.Tests/Properties/AssemblyInfo.cs
Release version `2.7.0`
Changelog:
* Add overwrite option to `Storage.Save` and make `AzureStorage` round trip bytes properly (#106)- Fix https://github.com/NuGet/NuGetGallery/issues/5175
> Merge dev into master

- src/NuGet.Services.Validation.Issues/ObsoleteTestingIssue.cs
- src/NuGet.Services.Validation.Issues/UnknownIssue.cs
- tests/NuGet.Services.Contracts.Tests/Validation/ValidationErrorCodeFacts.cs
> Fix unit tests

- src/NuGet.Services.Contracts/Validation/ValidationIssueCode.cs
- src/NuGet.Services.Validation.Issues/ValidationIssue.cs
- tests/NuGet.Services.Contracts.Tests/Validation/ValidationErrorCodeFacts.cs
- tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/785
> Add two new validation issues (reject counter signatures, reject non V1 signatures)

- src/NuGet.Services.Logging/TelemetryClientWrapper.cs
Fix from https://github.com/NuGet/ServerCommon/pull/141.
> Make TelemetryClientWrapper constructor public

- src/NuGet.Services.AzureManagement/AzureHelper.cs
- tests/NuGet.Services.AzureManagement.Tests/AzureHelperTests.cs
- tests/NuGet.Services.AzureManagement.Tests/NuGet.Services.AzureManagement.Tests.csproj
- tests/NuGet.Services.AzureManagement.Tests/project.json
Issue: https://github.com/NuGet/Engineering/issues/896
Fixes TSA bugs:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/462207
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/481902
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/462206
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/481903
> Fix TSA bugs

- src/NuGet.Services.Sql/ISqlConnectionFactory.cs
> Expose SQL conn props from factory interface

- src/NuGet.Services.AzureManagement/AzureManagementAPIWrapper.cs
- src/NuGet.Services.AzureManagement/IAzureManagementAPIWrapper.cs
Progress on https://github.com/NuGet/Engineering/issues/1527.
Make long lines more readable and used string interpolation instead of `string.Format`.
> Add RebootRoleInstanceAsync to allow programmatic rebooting of cloud service instance

- src/NuGet.Services.Contracts/Validation/ValidationIssueCode.cs
- src/NuGet.Services.Validation.Issues/ValidationIssue.cs
- tests/NuGet.Services.Contracts.Tests/Validation/ValidationErrorCodeFacts.cs
> SymbolErrorCodes

- build/sign.microbuild.targets
Progress on https://github.com/NuGet/Engineering/issues/1644
Progress on https://github.com/NuGet/Engineering/issues/1577
For an example of how this will be used, see:
https://github.com/NuGet/NuGet.Services.Metadata/commit/1d7cc265868148bf4fa24521193df3bd3b0e9e39
> Add sign.microbuild.targets

- build/sign.microbuild.targets
Progress on https://github.com/NuGet/Engineering/issues/1577
Found when enabling signing on shims.
> Make sure we define FilesToSign before SignFiles is run

- build/common.ps1
- build/runcodeanalysis.ps1
Fixes:
- Ensures output directory exists (for TSA upload)
- $SolutionPath for CI builds w/ submodules (e.g., "src/Gallery/submodules/NuGetGallery")
VSTS integration samples:
- [ServerCommon#41693](https://nuget.visualstudio.com/NuGetBuild/NuGetBuild%20Team/_build/results?buildId=41693&_a=summary&view=logs)
- [Validation.Orchestrator#41691](https://nuget.visualstudio.com/NuGetBuild/NuGetBuild%20Team/_build/results?buildId=41691&_a=summary&view=logs)
See: [TSA results](https://devdiv.visualstudio.com/DevDiv/_queries/query/59ab4b1e-5a91-4809-a315-2965ce60a54f)
> FxCop fixes for VSTS builds

- build/common.ps1
- build/nuget.codeanalysis.props
- build/runcodeanalysis.ps1
Required for https://github.com/NuGet/NuGetGallery/pull/6544
> Allow FxCop suppressions

- src/NuGet.Services.AzureManagement/AzureHelper.cs
- tests/NuGet.Services.Logging.Tests/TelemetryClientExtensionsTests.cs
1. Insecure DTD processing in XML - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/686576
2. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/697819
> Clean TSA warnings

- src/NuGet.Services.Messaging.Email/CoreMarkdownMessageService.cs
Aligning with https://github.com/NuGet/NuGetGallery/pull/6602
Didn't see any corresponding tests
> SendMessageInternalAsync should not call itself

- src/NuGet.Services.Contracts/ServiceBus/IBrokeredMessage.cs
- src/NuGet.Services.ServiceBus/BrokeredMessageWrapper.cs
- src/NuGet.Services.ServiceBus/SubscriptionProcessor.cs
This will help debugging of message duplication.
> Include the Service Bus message ID in the log scope

- tests/NuGet.Services.AzureManagement.Tests/NuGet.Services.AzureManagement.Tests.csproj
- tests/NuGet.Services.Configuration.Tests/NuGet.Services.Configuration.Tests.csproj
- tests/NuGet.Services.Contracts.Tests/NuGet.Services.Contracts.Tests.csproj
- tests/NuGet.Services.Cursor.Tests/DurableCursorFacts.cs
- tests/NuGet.Services.Cursor.Tests/NuGet.Services.Cursor.Tests.csproj
- tests/NuGet.Services.Entities.Tests/NuGet.Services.Entities.Tests.csproj
- tests/NuGet.Services.KeyVault.Tests/KeyVaultReaderFormatterFacts.cs
- tests/NuGet.Services.KeyVault.Tests/NuGet.Services.KeyVault.Tests.csproj
- tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj
- tests/NuGet.Services.Messaging.Email.Tests/NuGet.Services.Messaging.Email.Tests.csproj
- tests/NuGet.Services.Messaging.Tests/NuGet.Services.Messaging.Tests.csproj
- tests/NuGet.Services.Owin.Tests/NuGet.Services.Owin.Tests.csproj
- tests/NuGet.Services.ServiceBus.Tests/NuGet.Services.ServiceBus.Tests.csproj
- tests/NuGet.Services.Sql.Tests/NuGet.Services.Sql.Tests.csproj
- tests/NuGet.Services.Status.Tests/NuGet.Services.Status.Tests.csproj
- tests/NuGet.Services.Storage.Tests/NuGet.Services.Storage.Tests.csproj
- tests/NuGet.Services.Validation.Issues.Tests/NuGet.Services.Validation.Issues.Tests.csproj
- tests/NuGet.Services.Validation.Tests/NuGet.Services.Validation.Tests.csproj
Saving some bandwidth and cpu cycles :)
> Consolidate xunit and moq dependencies across solution

- build/common.ps1
I will use this to prototype deployment of an Azure Website.
> Add New-WebsitePackage

- build/common.ps1
I need to use latest dotnet version for e2e tests to build symbols test project.
> Update dotnet version in scripts

- NuGet.Server.Common.sln
- build.ps1
- src/NuGet.Services.FeatureFlags/FeatureFlagCacheService.cs
- src/NuGet.Services.FeatureFlags/FeatureFlagClient.cs
- src/NuGet.Services.FeatureFlags/FeatureFlagOptions.cs
- src/NuGet.Services.FeatureFlags/IFeatureFlagCacheService.cs
- src/NuGet.Services.FeatureFlags/IFeatureFlagClient.cs
- src/NuGet.Services.FeatureFlags/IFeatureFlagStorageService.cs
- src/NuGet.Services.FeatureFlags/IFeatureFlagTelemetryService.cs
- src/NuGet.Services.FeatureFlags/IFlightUser.cs
- src/NuGet.Services.FeatureFlags/Models/FeatureFlags.cs
- src/NuGet.Services.FeatureFlags/Models/FeatureStatus.cs
- src/NuGet.Services.FeatureFlags/Models/Flight.cs
- src/NuGet.Services.FeatureFlags/NuGet.Services.FeatureFlags.csproj
- src/NuGet.Services.FeatureFlags/Properties/AssemblyInfo.cs
- src/NuGet.Services.FeatureFlags/readme.md
- tests/NuGet.Services.FeatureFlags.Tests/FeatureFlagCacheServiceFacts.cs
- tests/NuGet.Services.FeatureFlags.Tests/FeatureFlagClientFacts.cs
- tests/NuGet.Services.FeatureFlags.Tests/FeatureFlagClientFlightFacts.cs
- tests/NuGet.Services.FeatureFlags.Tests/FeatureFlagStateBuilder.cs
- tests/NuGet.Services.FeatureFlags.Tests/NuGet.Services.FeatureFlags.Tests.csproj
- tests/NuGet.Services.FeatureFlags.Tests/Properties/AssemblyInfo.cs
Adds the client libraries for detecting the state of feature flags. Usage:
```csharp
IFeatureFlagClient features = ...;
IFeatureFlagUser currentUser = ...;
if (features.IsEnabled("NuGetGallery.TyposquattingDetection", defaultValue: false))
{
...
}
if (features.IsEnabled("NuGetGallery.TyposquattingDetection", currentUser, defaultValue: false))
{
...
}
```
Part of https://github.com/NuGet/NuGetGallery/issues/6788
Gallery integration: https://github.com/NuGet/NuGetGallery/pull/6806
> [Feature Flags] Add feature flag/flighting package

- src/NuGet.Services.FeatureFlags/FeatureFlagCacheService.cs
- src/NuGet.Services.FeatureFlags/IFeatureFlagCacheService.cs
- tests/NuGet.Services.FeatureFlags.Tests/FeatureFlagCacheServiceFacts.cs
Used by https://github.com/NuGet/NuGetGallery/pull/6895
> [Feature Flags] Expose the last refresh start time

- src/NuGet.Services.Contracts/Validation/ValidationIssueCode.cs
- src/NuGet.Services.Validation.Issues/ValidationIssue.cs
- tests/NuGet.Services.Contracts.Tests/Validation/ValidationErrorCodeFacts.cs
- tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs
Add new symbol issue for the case when the snupkg does not contain any symbols.
> Add new symbol issue for the case when the snupkg does not contain pdbs

- src/NuGet.Services.Contracts/Validation/ValidationIssueCode.cs
- src/NuGet.Services.Validation.Issues/ValidationIssue.cs
- tests/NuGet.Services.Contracts.Tests/Validation/ValidationErrorCodeFacts.cs
- tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs
Add issue for snupkg containing zipslip vulnerability.
> Add issue for snupkg containing zipslip vulnerability.

- build/common.ps1
> Update nuget.exe to latest (4.9.3) so that we can pack license expressions

- .nuget/packages.config
- build.ps1
Progress on https://github.com/NuGet/Engineering/issues/2244
> Perform package signing on the ServerCommon packages

- build/sign.microbuild.targets
Progress on https://github.com/NuGet/Engineering/issues/2243
> Enable code signing of third party dependencies in web app packages

- src/NuGet.Services.Validation/Entities/ValidationEntitiesContext.cs
- src/NuGet.Services.Validation/Migrations/ValidationMigrationsConfiguration.cs
Use the similar way like Gallery and Support Request to enable validation entities context to support migration job.
> [Database Migration] Validation database supports migration job. 

- tests/NuGet.Services.Validation.Tests/NuGet.Services.Validation.Tests.csproj
- tests/NuGet.Services.Validation.Tests/PendingMigrationsTests.cs
Addresses https://github.com/NuGet/NuGetGallery/issues/4934
Similar to https://github.com/NuGet/NuGetGallery/pull/7143
> Add pending migration test

- src/NuGet.Services.AzureManagement/NuGet.Services.AzureManagement.csproj
- src/NuGet.Services.Configuration/NuGet.Services.Configuration.csproj
- src/NuGet.Services.Contracts/NuGet.Services.Contracts.csproj
- src/NuGet.Services.Cursor/NuGet.Services.Cursor.csproj
- src/NuGet.Services.FeatureFlags/NuGet.Services.FeatureFlags.csproj
- src/NuGet.Services.Incidents/NuGet.Services.Incidents.csproj
- src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
- src/NuGet.Services.Logging/NuGet.Services.Logging.csproj
- src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj
- src/NuGet.Services.Sql/NuGet.Services.Sql.csproj
- src/NuGet.Services.Status.Table/NuGet.Services.Status.Table.csproj
- src/NuGet.Services.Status/NuGet.Services.Status.csproj
- src/NuGet.Services.Storage/NuGet.Services.Storage.csproj
- src/NuGet.Services.Validation.Issues/NuGet.Services.Validation.Issues.csproj
- src/NuGet.Services.Validation/NuGet.Services.Validation.csproj
- tests/NuGet.Services.AzureManagement.Tests/NuGet.Services.AzureManagement.Tests.csproj
- tests/NuGet.Services.Configuration.Tests/NuGet.Services.Configuration.Tests.csproj
- tests/NuGet.Services.Contracts.Tests/NuGet.Services.Contracts.Tests.csproj
- tests/NuGet.Services.FeatureFlags.Tests/NuGet.Services.FeatureFlags.Tests.csproj
- tests/NuGet.Services.KeyVault.Tests/NuGet.Services.KeyVault.Tests.csproj
- tests/NuGet.Services.ServiceBus.Tests/NuGet.Services.ServiceBus.Tests.csproj
- tests/NuGet.Services.Sql.Tests/NuGet.Services.Sql.Tests.csproj
- tests/NuGet.Services.Storage.Tests/NuGet.Services.Storage.Tests.csproj
- tests/NuGet.Services.Validation.Issues.Tests/NuGet.Services.Validation.Issues.Tests.csproj
- tests/NuGet.Services.Validation.Tests/NuGet.Services.Validation.Tests.csproj
- tools/AzureSqlConnectionTest/AzureSqlConnectionTest.csproj
https://nuget.visualstudio.com/NuGetBuild/_componentGovernance/113781?_a=alerts&typeId=585767&alerts-view-option=active
You can confirm that this resolves the component governance issues at https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=57168
> Update System.Net.Http to 4.3.4 and WindowsAzure.Storage to 9.3.3

- src/NuGet.Services.AzureManagement/NuGet.Services.AzureManagement.csproj
Upgrade package dependency to align the versions and resolve the conflicts.    
Run the unit tests locally, and it looks fine.
> Upgrade package dependency

- src/NuGet.Services.Logging/NuGet.Services.Logging.csproj
- tests/NuGet.Services.Logging.Tests/App.config
Part of https://github.com/NuGet/Engineering/issues/2527
> Update Application Insights to 2.3.0

- build/sign.microbuild.targets
Address https://github.com/NuGet/Engineering/issues/2619.
> Move to "Microsoft400" Authenticode certificate since "Microsoft" was deprecated

- build/common.ps1
Copied the relevant functions from NuGet/NuGet.Client repo.
> Ensure build script works on VS2019-only machine

- src/NuGet.Services.Validation/IPackageValidationEnqueuer.cs
- src/NuGet.Services.Validation/PackageValidationEnqueuer.cs
Address https://github.com/NuGet/NuGetGallery/issues/7490.
This is a breaking change so I will actively update ServerCommon everywhere to react to this.
> Rename StartValidationAsync to SendMessageAsync

- src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
Fixes https://github.com/NuGet/Engineering/issues/2508
> Upgrade Newtonsoft.Json dependency

- src/NuGet.Services.Logging/ApplicationInsights.cs
- src/NuGet.Services.Logging/NuGet.Services.Logging.csproj
Required for NuGet/Engineering#2537
> Add AppInsights heartbeat support

- src/NuGet.Services.Logging/DeploymentLabelEnricher.cs
- src/NuGet.Services.Logging/NuGet.Services.Logging.csproj
- tests/NuGet.Services.Logging.Tests/DeploymentLabelEnricherTests.cs
- tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj
Extracted the class from https://github.com/NuGet/NuGetGallery/pull/7713. Added tests.
> Added the `DeploymentLabelEnricher` to be shared between projects.

- src/NuGet.Services.Logging/NuGet.Services.Logging.csproj
Follow-up PR for https://github.com/NuGet/ServerCommon/pull/330 which somehow missed an unsaved change to the `csproj` file... 🤦‍♂
> Fix missing change to csproj

- .editorconfig
- Directory.Build.props
- NuGet.Server.Common.sln
- tests/NuGet.Services.Build.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Configuration.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Contracts.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.FeatureFlags.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Messaging.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Owin.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.ServiceBus.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Storage.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Validation.Issues.Tests/Properties/AssemblyInfo.cs
- tests/NuGet.Services.Validation.Tests/PendingMigrationsTests.cs
- tests/NuGet.Services.Validation.Tests/Properties/AssemblyInfo.cs
* Add static code analysis 
1. Add package reference 
2. Add global editor config
Address: https://github.com/NuGet/Engineering/issues/3417
> Add static code analysis

- src/NuGet.Services.Messaging.Email/NuGet.Services.Messaging.Email.csproj
Update reference for markdig
https://github.com/NuGet/Engineering/issues/3429
> upgrade markdig

- build/common.ps1
See:
https://devblogs.microsoft.com/nuget/getting-started-with-nuget-5-8/#known-issues
> Move to nuget.exe 5.8.0

- src/NuGet.Services.Licenses/NuGet.Services.Licenses.csproj
- src/NuGet.Services.Validation/NuGet.Services.Validation.csproj
Related to https://github.com/NuGet/NuGetGallery/issues/8230, https://github.com/NuGet/NuGetGallery/pull/8335.
Aligning client library versions with the Gallery.
> NuGet.* client libraries brough to the latest release

- src/NuGet.Services.KeyVault/CertificateUtility.cs
Need a common way to find certificate by subject for https://github.com/NuGet/Engineering/issues/4101 and similar items.
The function selects certificates with start date before now and end date after now and picks the most recent out of those.
> Find by subject certificate helper method.

- src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
- src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj
> [SB] Fix assembly warnings caused by version mismatch

- src/NuGet.Services.AzureManagement/NuGet.Services.AzureManagement.csproj
- src/NuGet.Services.Incidents/NuGet.Services.Incidents.csproj
- src/NuGet.Services.Logging/NuGet.Services.Logging.csproj
- src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj
- src/NuGet.Services.Status/NuGet.Services.Status.csproj
- src/NuGet.Services.Validation.Issues/NuGet.Services.Validation.Issues.csproj
Update Newtonsoft.json to 13.0.1 due to vulnerability
Addressing: https://github.com/NuGet/Engineering/issues/4452
> update newtonsoft.json version

- src/NuGet.Services.KeyVault/ISecretWriter.cs
- src/NuGet.Services.KeyVault/KeyVaultReader.cs
- src/NuGet.Services.KeyVault/KeyVaultWriter.cs
Progress on https://github.com/NuGet/Engineering/issues/3509
An interface and implementation for a key vault writer. Needed for a PAT rotator job.
> Key vault writer

- src/NuGet.Services.Licenses/NuGet.Services.Licenses.csproj
Updating to a more recent version of client libraries.
> Updating client libraries

- src/NuGet.Services.Licenses/NuGet.Services.Licenses.csproj
Address: https://github.com/NuGet/Engineering/issues/5251
> [CG]Update NuGet.Packaging

- .pipelines/ServerCommon-CI.yml
Progress on https://github.com/NuGet/Engineering/issues/5226.
YAML CI pipeline for ServerCommon repository.
> ServerCommon CI pipeline

- src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
- src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj
- src/NuGet.Services.Sql/NuGet.Services.Sql.csproj
Currently we have for 1.11.4 version PR: https://github.com/NuGet/ServerCommon/pull/428
But 1.12.0 is already out. We need to update to 1.12.0
Address: https://github.com/NuGet/Engineering/issues/5531
> update azure identity version

- README.md
Added steps for how to create a local database which is used for [NuGet.Jobs](https://github.com/NuGet/NuGet.Jobs/).
> Add how documentation for how to create local db

- src/NuGet.Services.Storage/AzureStorage.cs
Same as https://github.com/NuGet/NuGetGallery/pull/10101/files but for the ServerCommon copy of this code.
> Fetch and copy HTTP headers if they are being updated
