NuGet/ServerCommon

src/NuGet.Services.Configuration/ConfigurationUtility.cs, src/NuGet.Services.Configuration/DictionaryExtensions.cs, tests/NuGet.Services.Configuration.Tests/ConfigurationUtilityFacts.cs, tests/NuGet.Services.Configuration.Tests/DictionaryExtensionsFacts.cs
Currently, our jobs in `NuGet.Jobs` and our jobs in `NuGet.Services.Metadata` both use their own "TryGet" infrastructure. This manifests as [`JobConfigurationManager`](https://github.com/NuGet/NuGet.Jobs/blob/master/src/NuGet.Jobs.Common/Configuration/JobConfigurationManager.cs) in `NuGet.Jobs` and [`CommandHelpers`](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/CommandHelpers.cs) in `NuGet.Services.Metadata`.
I have added some extensions to `IDictionary<string, string>` to `NuGet.Services.Configuration` to consolidate the logic in a single place.
(`ConvertFromString` will also be using in the `SecretService` class for secret rotation and so it is in its own utility class.)
=> Added extensions to IDictionary<string, string> for ease of use in jobs

src/NuGet.Services.Configuration/DictionaryExtensions.cs, tests/NuGet.Services.Configuration.Tests/ConfigurationUtilityFacts.cs, tests/NuGet.Services.Configuration.Tests/DictionaryExtensionsFacts.cs
Rename `GetOrNull` to `GetOrDefault`.
Remove constraint on `GetOrThrow`.
Modified test cases appropriately.
=> Dictionary<string, string> Extensions 2.0

src/NuGet.Services.KeyVault/KeyVaultReader.cs
Spent far too long today debugging a stupid issue where the validation was incorrect but I thought it was a problem with the thumbprint. I think adding it to the exception message will improve debugging in the future.
=> improved the exception message if the certificate is not found

src/NuGet.Services.Configuration/DictionaryExtensions.cs, tests/NuGet.Services.Configuration.Tests/DictionaryExtensionsFacts.cs
This is part of the fix to https://github.com/NuGet/NuGet.Jobs/issues/73 (there will be another PR there). I have verified that the tests pass with this fix.
[It is consistent with behavior before the code was refactored.](https://github.com/NuGet/NuGet.Jobs/blob/master/src/NuGet.Jobs.Common/Configuration/JobConfigurationManager.cs#L104)
Also split the tests into more discrete units and added a new test to handle the new behavior.
=> Throw if null/empty value in dictionary for GetOrThrow

build/common.ps1, build/init.ps1
If web requests are made without this attribute, they will fail on machines that have not completed first-run configuration of Internet Explorer (VSTS hosted build agents).
=> UseBasicParsing for all web requests in Powershell

.gitignore, build.ps1, build/common.ps1, src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
This is necessary so that building all our projects will never lead to a changes on Git.
=> Use AssemblyInfo.g.cs pattern instead of appending to AssemblyInfo.cs

build/Queue-Build.ps1
After fixing another issue, builds of `NuGetDeployment` started failing when "refs/heads/branchname" was passed as the submodule branch instead of "branchname". This will fix that issue and get our builds running again!
=> Guarantee SubmoduleBranch is in no "refs/heads/" form

build/init.ps1
Due to how scopes in PowerShell work, this script was overwriting the branch variable when called using the dot operator.
For example,
```
$Branch = "master"
Write-Host $Branch
. "init.ps1" -Branch "dev"
Write-Host $Branch
```
outputs
```
master
dev
```
By moving the main logic entirely into a function and renaming the parameter to `$BuildBranch` we can prevent `$Branch`, `$RootGitHubApiUri`, `$Ref`, `$FoldersToDownload`, and `$Folder` from being overwritten.
=> Prevent init.ps1 from overwriting variables

build/common.ps1
With the addition of a new git submodule in our deployment repo, it became necessary to rewrite our submodule helper function to support greater configuration per submodule.
This change:
* Splits `Update-Submodules` into a couple of helper functions (`Reset-Submodules` and `Update-Submodule`).
* Deduplicates git invocation code through an `Invoke-Git` helper function.
=> Improve submodule support

build/common.ps1
With a single instance, PowerShell was unwrapping the array and returning the first character, not the first string.
=> Fix MSBuild 15 finder script to work with machines with single instances of VS2017

build/common.ps1
A dependency of `NuGet.Services.Build` was not found in `NuGet-Build` alone so the build was failing.
=> Use NuGet and NuGet-Build to install NuGet.Services.Build

src/NuGet.Services.Storage/NuGet.Services.Storage.csproj
Previous version did not pick up the `AssemblyInfo.g.cs` properly so we ended up with version `0.0.0.0`. This PR contains the fix
=> Included the proper file to have assembly version set properly

src/NuGet.Services.Logging/NuGet.Services.Logging.csproj, src/NuGet.Services.Logging/TelemetryResponseCodeProcessor.cs, tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj, tests/NuGet.Services.Logging.Tests/TelemetryResponseCodeProcessorFacts.cs
This adds the [Gallery's `TelemetryResponseCodeFilter`](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Telemetry/TelemetryResponseCodeFilter.cs) to this common repository so that it can be used by both the Gallery and the Search Service. I tweaked the name and added some basic tests.
Related to [Gallery #3793](https://github.com/NuGet/NuGetGallery/issues/3793)
=> Add Application Insights Processor for Response Codes

src/NuGet.Services.Logging/TelemetryResponseCodeProcessor.cs, tests/NuGet.Services.Logging.Tests/TelemetryResponseCodeProcessorFacts.cs
Application Insight's configuration file doesn't play nice with configurable properties that are arrays. This changes the `TelemetryResponseCodeProcessor` to use an `IList` to follow the pattern set by Application Insight's `RequestTrackingTelemetryModule`'s `Handlers` configurable property.
=> Tweaked TelemetryResponseCodeProcessor 

src/NuGet.Services.Owin/ForceSslMiddleware.cs, src/NuGet.Services.Owin/ForceSslMiddlewareExtensions.cs, tests/NuGet.Services.Owin.Tests/ForceSslMiddlewareFacts.cs, tests/NuGet.Services.Owin.Tests/project.json
Added the exclusion list to the ForceSslMiddleware.
Added tests for the change.
=> ForceSslMiddleware now allows to exclude certain paths from redirection.

NuGet.Server.Common.sln, build.ps1, src/NuGet.Services.Cursor/AggregateCursor.cs, src/NuGet.Services.Cursor/DurableCursor.cs, src/NuGet.Services.Cursor/HttpReadCursor.cs, src/NuGet.Services.Cursor/MemoryCursor.cs, src/NuGet.Services.Cursor/NuGet.Services.Cursor.csproj, src/NuGet.Services.Cursor/Properties/AssemblyInfo.cs, src/NuGet.Services.Cursor/ReadCursor.cs, src/NuGet.Services.Cursor/ReadWriteCursor.cs, src/NuGet.Services.Cursor/project.json, tests/NuGet.Services.Cursor.Tests/AggregateCursorTests.cs, tests/NuGet.Services.Cursor.Tests/DurableCursorFacts.cs, tests/NuGet.Services.Cursor.Tests/NuGet.Services.Cursor.Tests.csproj, tests/NuGet.Services.Cursor.Tests/Properties/AssemblyInfo.cs, tests/NuGet.Services.Cursor.Tests/project.json
Copied cursors from the Nuget.Services.Metadata.
Made the base classes generics.
Made the concrete classes to use `DateTimeOffset` types instead of `DateTime` - migration should be pretty easy since the serialization is done with `dateTime.ToString("O")` and serialized string can be deserialized to `DateTimeOffset` without any additional effort.
Added tests for the `DurableCursor` class.
=> Added Nuget.Services.Cursor project

src/NuGet.Services.Configuration/ConfigurationRootSecretReaderFactory.cs, src/NuGet.Services.KeyVault/CertificateUtility.cs, src/NuGet.Services.KeyVault/KeyVaultConfiguration.cs, src/NuGet.Services.KeyVault/KeyVaultReader.cs, src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
The V3 monitoring job must use another means to find the certificate rather than by the thumbprint. This change will allow me to find the certificate myself and then pass it to my `KeyVaultReader`.
=> Support specifying KeyVault certificate directly rather than by thumbprint

build/common.ps1
Fix the NuGet version used by our build to 4.1.0, instead of "latest-prerelease" which points to 4.0.0.
=> Fix NuGet version used by build scripts to 4.1.0

NuGet.Server.Common.sln, src/NuGet.Services.KeyVault/CachingSecretReader.cs, src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj, src/NuGet.Services.ServiceBus/ScopedMessageHandler.cs, src/NuGet.Services.ServiceBus/project.json, tests/NuGet.Services.KeyVault.Tests/CachingSecretReaderFacts.cs, tests/NuGet.Services.ServiceBus.Tests/NuGet.Services.ServiceBus.Tests.csproj, tests/NuGet.Services.ServiceBus.Tests/ScopedMessageHandlerFacts.cs
Often times, Service Bus message handlers will need to use some sort of Entity Framework context. This requires that the handlers' callbacks are executed within their own dependency injection scope. This change creates a new generic Service Bus message handler `ScopedMessageHandler` that, upon receiving a message, creates a new dependency injection scope.
This change also makes `CachingSecretReader` thread-safe, as otherwise, the `ScopedMessageHandler` would need a lock.
=> [Package Signing] Added a Scoped Service Bus Message Handler

src/NuGet.Services.Storage/AggregateStorage.cs, src/NuGet.Services.Storage/AzureStorage.cs, src/NuGet.Services.Storage/FileStorage.cs, src/NuGet.Services.Storage/IStorage.cs, src/NuGet.Services.Storage/Storage.cs
All of the concrete implementations of `IStorage` already implemented the `Exists(string)` method, but it was not exposed on the interface. This PR adds it to the interface, and adds an async overload (which is useful when consuming a storage abstraction that supports async I/O).
Will be used by `ICertificateStore` implementation in validation job.
=> Expose Exists API on IStorage + add Async overload

NuGet.Server.Common.sln, src/NuGet.Services.Cursor/DurableCursor.cs, src/NuGet.Services.Storage/AggregateStorage.cs, src/NuGet.Services.Storage/AzureStorage.cs, src/NuGet.Services.Storage/FileStorage.cs, src/NuGet.Services.Storage/IStorage.cs, src/NuGet.Services.Storage/Storage.cs, tests/NuGet.Services.Storage.Tests/AzureStorageFacts.cs, tests/NuGet.Services.Storage.Tests/NuGet.Services.Storage.Tests.csproj, tests/NuGet.Services.Storage.Tests/Properties/AssemblyInfo.cs
Fix https://github.com/NuGet/NuGetGallery/issues/5175.
Tests are skipped because they need Azure Storage emulator to run them.
This PR is currently blocking https://github.com/NuGet/NuGet.Jobs/pull/280.
=> Round trip bytes properly and allow no overwrite in Storage abstraction

src/NuGet.Services.ServiceBus/Event.cs, src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj, src/NuGet.Services.ServiceBus/SubscriptionProcessor.cs
Previously exception was logged in the message body converting the exception object to string, that caused truncation and loss of full stack trace.
By logging it this way we'll have structured exception information in AI entry.
=> Better exception logging in SubscriptionProcessor.

src/NuGet.Services.Validation.Issues/ClientSigningVerificationFailure.cs, src/NuGet.Services.Validation.Issues/ObsoleteTestingIssue.cs, src/NuGet.Services.Validation.Issues/SignedPackageMustHaveOneSignature.cs, src/NuGet.Services.Validation.Issues/ValidationIssue.cs, tests/NuGet.Services.Validation.Issues.Tests/Strings.Designer.cs, tests/NuGet.Services.Validation.Issues.Tests/Strings.resx, tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs
Address https://github.com/NuGet/NuGetGallery/issues/5265.
The goal here is to show a generic error message to users in the gallery when there is some deserialization problem.
=> When an issue has bad data, deserialize the issue as UnknownIssue

src/NuGet.Services.ServiceBus/ISubscriptionProcessor.cs, src/NuGet.Services.ServiceBus/SubscriptionProcessor.cs, tests/NuGet.Services.ServiceBus.Tests/SubscriptionProcessorFacts.cs
Today, the Orchestrator has custom code to ensure that:
1. New Service Bus messages are dropped once shutdown has started
2. Shutting down Service Bus does not block the current thread
This brings the logic to the `SubscriptionProcessor` so that all other jobs can also have these guarantees.
Part of https://github.com/NuGet/Engineering/issues/1115
=> [Service Bus] Add timeout to shutdown

src/NuGet.Services.ServiceBus/SubscriptionProcessor.cs
Added a scope around message processing in SubscriptionProcessor that should make it easier to correlate log entries across library boundaries.
A guid is generated per call, plus `DateTimeOffset.UtcNow.Ticks` is reported. The latter would allow grouping and ordering single call logs by start time. The former would allow to distinguish between calls in case they are close enough so that Ticks are the same.
=> Scope around ServiceBus message processing

src/NuGet.Services.Contracts/ServiceBus/IBrokeredMessage.cs, src/NuGet.Services.ServiceBus/BrokeredMessageWrapper.cs, src/NuGet.Services.Validation/PackageValidationMessageData.cs, src/NuGet.Services.Validation/ServiceBusMessageSerializer.cs, tests/NuGet.Services.Validation.Tests/ServiceBusMessageSerializerTests.cs
Adds the Service Bus message's delivery count to `PackageValidationMessageData`. This will allow the Orchestrator to make decisions based off how many times a validation message has been tried.
Progress on https://github.com/NuGet/Engineering/issues/1100
=> [Orchestrator] Expose the Service Bus delivery count

src/NuGet.Services.Contracts/Logging/ITelemetryClient.cs, src/NuGet.Services.Contracts/NuGet.Services.Contracts.csproj, src/NuGet.Services.Logging/NuGet.Services.Logging.csproj, src/NuGet.Services.Logging/TelemetryClientWrapper.cs
This moves the implementation from NuGetGallery to ServerCommon.
This is helpful for unit tests `Track*` methods on `TelemetryService`.
=> Add ITelemetryClient and TelemetryClientWrapper

src/NuGet.Services.Logging/DurationMetric.cs, src/NuGet.Services.Logging/NuGet.Services.Logging.csproj, src/NuGet.Services.Logging/TelemetryClientExtensions.cs, tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj, tests/NuGet.Services.Logging.Tests/TelemetryClientExtensionsTests.cs
Add a `TrackDuration` method. This allows you to easily instrument duration of code like so:
```cs
using (_telemetryClient.TrackDuration("my_service.time_to_download_package"))
{
// Do some expensive operation whose duration should be tracked
_packageDownloadService.DownloadPackage("My.Package", "1.0.0");
}
```
=> Add TrackDuration extension

src/NuGet.Services.Contracts/Validation/ValidationIssueCode.cs, src/NuGet.Services.Validation.Issues/ValidationIssue.cs, tests/NuGet.Services.Contracts.Tests/Validation/ValidationErrorCodeFacts.cs, tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/1207
We will start stripping repository signatures so the old `AuthorAndRepositoryCounterSignaturesNotSupported` issue is not longer needed.
=> Add AuthorCounterSignaturesNotSupported issue

src/NuGet.Services.Storage/AzureStorageQueue.cs, src/NuGet.Services.Storage/AzureStorageQueueMessage.cs, src/NuGet.Services.Storage/DeserializedStorageQueueMessage.cs, src/NuGet.Services.Storage/StorageQueue.cs, src/NuGet.Services.Storage/StorageQueueMessage.cs
So I don't need this shenanigans:
https://github.com/NuGet/NuGet.Services.Metadata/blob/e18d2e1811e95537bc2f4da5196303601d893e10/src/V3PerPackage/PerWorkerProcessor.cs#L102-L116
=> Add dequeue count to NuGet.Services.Storage queue abstraction

src/NuGet.Services.Contracts/Validation/ValidationIssueCode.cs, src/NuGet.Services.Validation.Issues/NuGet.Services.Validation.Issues.csproj, src/NuGet.Services.Validation.Issues/UnauthorizedCertificateFailure.cs, src/NuGet.Services.Validation.Issues/ValidationIssue.cs, tests/NuGet.Services.Contracts.Tests/Validation/ValidationErrorCodeFacts.cs, tests/NuGet.Services.Validation.Issues.Tests/Strings.Designer.cs, tests/NuGet.Services.Validation.Issues.Tests/Strings.resx, tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs
Add a new issue for the signature validation failure when a package is signed with a certificate that is not known to the package's signing owner(s).
=> Certificates:  add new validation issue

src/NuGet.Services.Validation/Entities/IValidationContext.cs
#151 added `ScanOperationStates` to implementation, but wasn't added to the interface.
=> Missed update to IValidationEntitiesContext

src/NuGet.Services.Sql/AzureSqlConnectionFactory.cs, src/NuGet.Services.Sql/AzureSqlConnectionStringBuilder.cs
Adds `DataSource` and `InitialCatalog` connection string properties off `ISqlConnectionFactory`, as some jobs are logging these to AI.
=> Expose SQL connection string properties

src/NuGet.Services.Sql/AzureSqlConnectionFactory.cs, src/NuGet.Services.Sql/ISqlConnectionFactory.cs, tests/NuGet.Services.Sql.Tests/AzureSqlConnectionFactoryFacts.cs
Fixes: https://github.com/NuGet/Engineering/issues/1472
Related: https://github.com/NuGet/NuGetGallery/pull/6063
Will use `CreateAsync` when used with EF so that the open can be deferred and controlled fully by the `DbContext`.
=> Allow deferred connections from SqlConnectionFactory

src/NuGet.Services.ServiceBus/SubscriptionProcessor.cs, tests/NuGet.Services.ServiceBus.Tests/SubscriptionProcessorFacts.cs
Additionally, moved logging scope to contain "try .. catch" so exceptions logged have CallGuid in their scope.
Addresses https://github.com/NuGet/Engineering/issues/1500
=> Not allowing exceptions to leave the subscription processor.

src/NuGet.Services.ServiceBus/ISubscriptionProcessorTelemetryService.cs, src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj, src/NuGet.Services.ServiceBus/SubscriptionProcessor.cs, src/NuGet.Services.ServiceBus/SubscriptionProcessorNoTelemetryService.cs, tests/NuGet.Services.ServiceBus.Tests/SubscriptionProcessorFacts.cs
Added the `ISubscriptionProcessorTelemetryService` that would allow to export two metrics from the Service Bus client:
* Message delivery lag - the time between when the message was supposed to be enqueued for delivery to the client and the actual delivery time. Larger (>~1 second) values of the metric would indicate congestion when processing service bus messages (i.e. we are receiving more messages than processing);
* Enqueue lag - the time between when the message was supposed to be enqueued for delivery and actual enqueuing time. The values greater than zero here would indicate some sort of issues on Service Bus side, so I expect this metric to be zero or near-zero 100% of the time. But if it is not, it would hopefully save us time on debugging some funny issues.
Since it's a breaking …
=> Service bus telemetry

NuGet.Server.Common.sln, src/NuGet.Services.Sql/AzureSqlConnectionFactory.cs, tools/AzureSqlConnectionTest/App.config, tools/AzureSqlConnectionTest/AzureSqlConnectionTest.csproj, tools/AzureSqlConnectionTest/Program.cs, tools/AzureSqlConnectionTest/Properties/AssemblyInfo.cs, tools/AzureSqlConnectionTest/TestApplication.cs, tools/AzureSqlConnectionTest/TestRunner.cs
Allows for testing:
- Concurrent connections using the same AAD credentials, same access tokens
- Concurrent connections in-proc or out-of-proc
- Short- or long-lived connections
- Long-lived connections that are idle
- Using latest `NuGet.Services.Sql` or default ADAL
Based on initial tests, doesn't seem like there's a limit on # connections per certificate or access token... though I need to test with longer runs. I haven't been able to repro the original "Login failed for user" exceptions yet, which seemed to happen after deploying N jobs.
I have seen the following exception if I add a breakpoint after initial connection open, but retry succeeds. Will investigate this.
```
Test started: 10 clients, 60s duration, 15s interval, persist = False, adal = False
Failed …
```
=> Tool for running SQL AAD connection tests

build/init.ps1
https://github.com/NuGet/NuGetGallery/issues/6334
We have a minor "null reference" bug with `init.ps1`, but we haven't noticed it yet because our build machines have strict mode off and the script works anyway due to some coincidences with how PowerShell works.
=> Fix $FilePath bug with init.ps1

build/common.ps1
Add `New-Package` replacement that includes dependencies when building projects that use PackageReferences. This is based on the workaround from @rohit21agrawal in https://github.com/NuGet/Home/issues/5979
Requirement for https://github.com/NuGet/NuGetGallery/issues/6348
=> Build function to pack PackageReference projects with dependencies

build/common.ps1, build/nuget.codeanalysis.props, build/runcodeanalysis.ps1
Tracking: https://github.com/NuGet/Engineering/issues/822
Issues with our current way of running FxCop (VSTS build task):
- Single invocation for all solution assemblies, which can result in runtime dependency conflicts
- Does not set CODE_ANALYSIS flag, so code suppressions would not be preserved
- Target discovery assumes project and assembly names match
- Hard to debug on dev machines
Proposal here is to use the `RunCodeAnalysis` msbuild task to invoke FxCop. By default, it uses the instance installed with VS and the minimum ruleset. This also supports custom FxCop installation, project and ruleset - which will be used by our build agents.
Currently, I've only tested against `NuGet.Services.Metadata` but will be testing other repos before I merge.
=> Add default and custom FxCop support

build/common.ps1
Accidentally broke the scenario where $FxCopOutputDirectory isn't set
=> FxCop script fix

src/NuGet.Services.Validation/PackageValidationMessageData.cs, src/NuGet.Services.Validation/ServiceBusMessageSerializer.cs, tests/NuGet.Services.Validation.Tests/ServiceBusMessageSerializerTests.cs, tests/NuGet.Services.Validation.Tests/TestData.Designer.cs, tests/NuGet.Services.Validation.Tests/TestData.resx
We need to pass `PackageKey` in the message from gallery so that `Orchestrator` can perform appropriate actions for revalidating a symbols package. The idea is we will not pass `PackageKey`(or null) in the message when a package is pushed for validation(first time) with revalidation we will pass in the `Key` for the entity. 
I am open to generalizing this and naming it `EntityKey` or `Key`, I kept it `PackageKey` in context to that of the `PackageId` and `PackageVersion` in the message.
=> Add entity key to PackageValidationMessageData

build/sign.microbuild.targets, build/sign.scripts.targets
https://github.com/NuGet/Engineering/issues/1728
This PR consists of two changes:
1 - We need to set `MicroBuild_NuPkgSigningEnabled` to false so that it doesn't automatically sign the nupkgs we produce (we are not required to sign them).
2 - Adding `sign.scripts.targets` that will be used by both `NuGet.Services.Metadata` and `NuGet.Jobs` to sign the `Scripts\` files.
=> Changes to signing targets for job MicroBuild integration

build/common.ps1
I'm seeing `build.ps1` throw when certain AzureRm modules are loaded. The cause appears to be a dependency conflict for assembly `Microsoft.WindowsAzure.Storage`. Suggested fix is to not enumerate types, just check if the build assembly is loaded.
**Failing Assemblies:**
- C:\Program Files\WindowsPowerShell\Modules\AzureRM.RedisCache\4.1.2\Microsoft.Azure.Insights.dll
- C:\Program Files\WindowsPowerShell\Modules\Azure\5.1.2\HDInsight\Microsoft.Hadoop.Client.dll
**Repro (Step 3 from `common.ps1`):**
> \> Get-Module
> \> Get-Command -Module AzureRm | Out-Null
> \> [AppDomain]::CurrentDomain.GetAssemblies() | ForEach-Object { $a = $_; try { $a.GetTypes()>$null } catch { Write-Host $_; Write-Host $a.Location } } >$null
> \> Get-module
**Exception:**
BUILD FAILED: Exception calling "GetTypes" …
=> Fix GetTypes exception when AzureRm modules loaded

build/NuGet.Sdl7.0.ruleset, build/common.ps1, src/NuGet.Services.AzureManagement/AzureHelper.cs
Tracking: https://github.com/NuGet/Engineering/issues/1757
**Includes:**
- Add support for SDL ruleset overrides (currently ignoring CA1305 and CA1307 due to volume)
- Builds will have "FxCopRuleSet" parameter, and overrides applied to highest volume repos
- Suppress **Microsoft.Security #CA3053:UseXmlSecureResolver** errors, which fxcop incorrectly reports
- Fix the following warnings:
- **Microsoft.Security #CA2104:DoNotDeclareReadOnlyMutableReferenceTypes**
- **Microsoft.Globalization #CA1304:SpecifyCultureInfo**
- **Microsoft.Globalization #CA1309:UseOrdinalStringComparison**
**Summary of TSA issues:**
- **Microsoft.Globalization #CA1304:SpecifyCultureInfo**
- Total: 20
- NuGetGallery: 10
- NuGet.Services.Metadata: 9
- ServerCommon: 1 (fixed here)
- **Microsoft.Globalization …
=> FxCop override support and fixes

build/NuGet.Sdl7.0.ruleset
Exclude **CA2105:ArrayFieldsShouldNotBeReadOnly**, for NuGet.Services.Metadata and NuGet.Internal.Jobs
Similar to **CA2104:DoNotDeclareReadOnlyMutableReferenceTypes**, but for array types.
=> Add CA2105 exclusion

src/NuGet.Services.Messaging.Email/AsynchronousEmailMessageService.cs, tests/NuGet.Services.Messaging.Email.Tests/AsynchronousEmailMessageServiceFacts.cs
The field is unused, and having to create an implementation of `IMessageServiceConfiguration` and give it dummy values to use this class seems overkill.
=> Remove unnecessary IMessageServiceConfiguration constructor parameter from AsynchronousEmailMessageService

src/NuGet.Services.Contracts/Validation/ValidationIssueCode.cs, src/NuGet.Services.Messaging.Email/Extensions/ValidationIssueExtensions.cs, src/NuGet.Services.Validation.Issues/ValidationIssue.cs, tests/NuGet.Services.Contracts.Tests/Validation/ValidationErrorCodeFacts.cs, tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs
On error was used for both cases: when the pdb is not portable or when a pdb did not have a corresponding dll.  Split the error is two.
=> Divided symbol error message

build.ps1, build/common.ps1, build/sign.microbuild.targets
https://github.com/NuGet/Engineering/issues/1887
Now: 50 minutes
After: 7 minutes
How did I do it?
- Build and sign solution in parallel (`/m`)
- Turn off signing when packing (`/p:SignType:none`)
- Sign intermediate assemblies in `sign.microbuild.targets` (necessary because otherwise `New-ProjectPackage` will replace the signed output assemblies with the unsigned intermediate assemblies)
I expect we can get similar wins by doing this in our other repositories as well.
Additionally, I changed our `verbosity` from `minimal` back to the default. I did this because I think it will make it easier for us to debug build issues in the future.
=> Improve signing time of ServerCommon

src/NuGet.Services.Status/ActiveActiveComponent.cs, src/NuGet.Services.Status/Component.cs, src/NuGet.Services.Status/TreeComponent.cs, tests/NuGet.Services.Status.Tests/ComponentWithSubComponentsTests.cs
Accidentally merged https://github.com/NuGet/ServerCommon/pull/186 without realizing that it needs to set `displaySubComponents` to `false` or else its subcomponents will appear on the status page (e.g. `Search Global USNC` and `Search Global USSC`).
To make sure this doesn't happen again, I also made it so that `displaySubComponents` must now be explicitly stated in each `Component` implementation. I also added a test that verifies that each `Component` implementation sets it properly.
=> Fix "displaySubComponents" of ActiveActiveComponent

src/NuGet.Services.ServiceBus/BrokeredMessageWrapper.cs, src/NuGet.Services.ServiceBus/ISubscriptionProcessorTelemetryService.cs, src/NuGet.Services.ServiceBus/SubscriptionProcessor.cs, src/NuGet.Services.ServiceBus/SubscriptionProcessorNoTelemetryService.cs, tests/NuGet.Services.Configuration.Tests/DictionaryExtensionsFacts.cs, tests/NuGet.Services.Configuration.Tests/SecretDictionaryFacts.cs, tests/NuGet.Services.Owin.Tests/NuGet.Services.Owin.Tests.csproj, tests/NuGet.Services.ServiceBus.Tests/SubscriptionProcessorFacts.cs, tests/NuGet.Services.Validation.Issues.Tests/ValidationIssuesFacts.cs, tests/NuGet.Services.Validation.Tests/ServiceBusMessageSerializerTests.cs
Today, we have to parse Application Insights logs to figure out how a message handler's duration. This makes it impossible to dashboard and monitor. This metric will let us detect messages that caused deadlettering by exceeding their expected duration.
I also fixed a bunch of build warnings as part of this change.
Part of: https://github.com/NuGet/NuGetGallery/issues/6624
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2228537&view=logs
=> Improve SubscriptionProcessor's telemetry for messages exceeding expected duration

src/NuGet.Services.Configuration/ConfigurationBuilderExtensions.cs, src/NuGet.Services.Configuration/KeyVaultEnvironmentVariableInjectingConfigurationSource.cs, src/NuGet.Services.Configuration/NuGet.Services.Configuration.csproj, tests/NuGet.Services.Configuration.Tests/ConfigurationBuilderExtensionsFacts.cs, tests/NuGet.Services.Configuration.Tests/NuGet.Services.Configuration.Tests.csproj
This will enable configuration for Web Apps.
This is the ARM resource that sets configuration on an Azure slot.
```json
{
"apiVersion": "2018-02-01",
"name": "appsettings",
"type": "config",
"dependsOn": [
"[resourceId('Microsoft.Web/sites/slots', parameters('websiteName'), variables('slotName'))]"
],
"properties": "[parameters('appSettings')]"
}
```
This is a trimmed example of the parameters file:
```json
{
"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
"contentVersion": "1.0.0.0",
"parameters": {
"appSettings": {
"value": {
"SearchService:SearchServiceName": "jver-search"
}
}
}
}
```
The environment variables come out like this at runtime.
**Key**: `APPSETTING_SearchService:SearchServiceName`
**Value**: `jver-search`
The benefit of this …
=> Enable KeyVault injection into environment variables

build/common.ps1
This is needed for https://github.com/nuget/engineering/issues/2249 because `NuGet.Status` has a `NuGetGallery` submodule which becomes a nested submodule when `NuGet.Status` is a submodule inside `NuGetDeployment`.
=> Add recursive to common.ps1 submodules cmdlets

build/common.ps1, build/sign.proj
Progress on https://github.com/NuGet/Engineering/issues/2242
Progress on https://github.com/NuGet/Engineering/issues/2243
Progress on https://github.com/NuGet/Engineering/issues/2244
You can just do `Sign-Packages` and it will sign all .nupkgs in artifacts directory. This already works in NuGet.Server.
=> Add sign.proj which runs package signing on all artifacts nupkgs

build/sign.microbuild.targets
Progress on https://github.com/NuGet/Engineering/issues/2243.
`WebPublishMethod` is defined in the packaging method:
https://github.com/NuGet/ServerCommon/blob/88a27e60b13934055273a3f813c426d738cc70be/build/common.ps1#L676
`PipelineCopyAllFilesToOneFolderForMsdeployDependsOn` is found in the targets that implement the packaging allowing us to hook in during the packaging process.
=> Support signing during the web app packaging step

src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj
=> Explicitly require Newtonsoft.Json dependency to be minimum v9.0.1

build/common.ps1
- use `deinit` instead of `foreach --recursive git reset --hard` because it is the proper way to deinitialize submodules
- remove `--recursive` in `Update-Submodule`
- `--recursive` causes the build to update all nested submodules with their latest `master`, but this is not what we want for `NuGet.Services.Status` because its `NuGetGallery` submodule is intended to remain on a specific commit until it is updated
- I have modified `NuGet.Services.Status`'s build script to manually update the `NuGetGallery` submodule with the commit in the repository (`git submodule update --init -- <path>`)
- This should not affect any builds, because `NuGet.Services.Status` is our only repository with nested submodules, and the only build updated to a version of ServerCommon with it is `NuGet.Licenses`
- …
=> Submodule fixes for NuGet.Services.Status build

src/NuGet.Services.FeatureFlags/FeatureFlagClient.cs, src/NuGet.Services.FeatureFlags/IFeatureFlagClient.cs, tests/NuGet.Services.FeatureFlags.Tests/FeatureFlagClientFlightFacts.cs
The gallery signifies a user that's not logged in as a `null` value, which wasn't handled properly.
Build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2530168
=> [Feature Flags] Handle nulls as anonymous users

src/NuGet.Services.Sql/AzureSqlConnectionFactory.cs
The SQL connection factory emits a log of how long until the SQL AAD token expires each time it does a SQL query. This accounts for ~25% of the Gallery's logs (as many as 40M logs per day). I've removed this log as it adds little value.
Part of https://github.com/NuGet/NuGetGallery/issues/7025
=> [SQL AAD] Reduce Gallery's logging by ~25%

src/NuGet.Services.ServiceBus/OnMessageOptionsWrapper.cs, src/NuGet.Services.ServiceBus/SubscriptionClientWrapper.cs
Progress on https://github.com/NuGet/Engineering/issues/1931
Had to change `OnMessageOptionsWrapper` to not keep the instance of `OnMessageOptions` but produce one on demand so that the lifetime of that object can be controlled by the caller. The reason to do it was that `SubscriptionClientWrapper` now adds an event to the instance of `OnMessageOptions`, so any additional references to `OnMessageOptions` would extend the life time of `SubscriptionClientWrapper`, which is likely not desired.
With the current code it is guaranteed that `SubscriptionClientWrapper` will be the sole owner of the `OnMessageOptions` and no lifetime extension would happen.
=> Exception logging for exceptions leaked to ServiceBus SDK.

src/NuGet.Services.KeyVault/EmptySecretReader.cs, src/NuGet.Services.KeyVault/IRefreshableSecretReaderFactory.cs, src/NuGet.Services.KeyVault/ISecret.cs, src/NuGet.Services.KeyVault/ISecretReader.cs, src/NuGet.Services.KeyVault/KeyVaultSecret.cs, src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj, src/NuGet.Services.KeyVault/RefreshableSecretReader.cs, src/NuGet.Services.KeyVault/RefreshableSecretReaderFactory.cs, src/NuGet.Services.KeyVault/RefreshableSecretReaderSettings.cs, tests/NuGet.Services.KeyVault.Tests/NuGet.Services.KeyVault.Tests.csproj, tests/NuGet.Services.KeyVault.Tests/RefreshableSecretReaderFactoryFacts.cs, tests/NuGet.Services.KeyVault.Tests/RefreshableSecretReaderFacts.cs
1. Add `RefreshSecretReader`. This returns a secret from cache if it exists. The cache lifetime from this class's perspective is forever. If the secret does not exist in the cache, it will be fetched from an underlying secret reader.
1. Add `RefreshSecretReaderFactory`. This holds the reference to the shared secret cache and has a method `RefreshAsync` which is on `IRefreshSecreReaderFactory` that can be called from a "safe" context, e.g. background thread in a web app.
I added a thing called `BlockUncachedReads` which makes is so non-`RefreshAsync` paths cannot read secrets from KeyVault. In other words it means the secret must be in the cache. This is added so that if we have a bug and a request context tries to read a secret, we throw an exception to fail fast instead of deadlocking. …
=> Add RefreshableSecretReader to allow background thread secret refresh

src/NuGet.Services.ServiceBus/BrokeredMessageSerializer.cs, src/NuGet.Services.Validation/CheckValidatorData.cs, src/NuGet.Services.Validation/NuGet.Services.Validation.csproj, src/NuGet.Services.Validation/PackageValidationMessageData.cs, src/NuGet.Services.Validation/PackageValidationMessageType.cs, src/NuGet.Services.Validation/ProcessValidationSetData.cs, src/NuGet.Services.Validation/ServiceBusMessageSerializer.cs, tests/NuGet.Services.Validation.Tests/ServiceBusMessageSerializerTests.cs, tests/NuGet.Services.Validation.Tests/TestData.Designer.cs, tests/NuGet.Services.Validation.Tests/TestData.resx
Progress on https://github.com/nuget/nugetgallery/issues/7354.
As spec'd in the Queue Back design this adds a message type for orchestrator that just contains the validation ID so that downstream validations can notify orchestrator that they are done.
=> Add notion of "check validator" message for orchestrator

src/NuGet.Services.FeatureFlags/FeatureFlagCacheService.cs
Right now the `RunAsync` task will wait up to `RefreshInterval` before completing even when cancelled.
It can stop immediately allowing faster shutdown.
Related to https://github.com/NuGet/NuGetGallery/issues/7439.
=> Allow the delay in the feature flag refresh loop to be cancelled

build/FindDuplicateFiles.targets, build/sign.microbuild.targets
Builds on https://github.com/NuGet/ServerCommon/pull/312. We have non-batch signing cases where build and publish are in the same MSBuild invocation. In such cases, we can't batch sign. We just sign in between the build and publish steps.
=> De-dupe files to sign in non-batch signing case

build/init.ps1
Use a marker file to no-op the download.
I have had situations locally where I get throttled by GitHub because I downloaded too many files from raw.githubusercontent.com using unauthenticated requests.
=> Don't re-download build tools directory every time

src/NuGet.Services.Logging/ApplicationInsights.cs
Facilitates debugging potential AI config issues. If `HeartbeatManager` is not configured/found, this will clearly tell us.
=> Add traces to emit telemetry initialization and heartbeat config

src/NuGet.Services.Logging/NuGet.Services.Logging.csproj
Many consumers of ServerCommon dependencies already manually added and upgraded the `Microsoft.Extensions.Logging` dependency to version 1.1.2.
All other ServerCommon libraries already use version 1.1.2. Only `NuGet.Services.Logging` was lagging behind to version 1.0.0.
This PR updates and aligns this dependency for `NuGet.Services.Logging`, and allows us to remove the explicit top-level dependency to `Microsoft.Extensions.Logging` elsewhere, making it a transitive one instead, which makes it easier to maintain our dependencies across the board.
=> Align Microsoft.Extensions.Logging dependency for ServerCommon solution

src/NuGet.Services.Logging/ApplicationInsights.cs
I noticed we're missing traces from the [`ApplicationInsights.Initialize` method](https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.Logging/ApplicationInsights.cs#L28).
The following AI query returns zero results for e.g. EmailPublisher job:
```
traces
| where message contains "Telemetry init" 
```
Confirmed that these traces now do end up in AI.
=> Use TelemetryClient instead of SysDiag.Trace to trace AI initialization

build/common.ps1
Should address some of the CredentialProvider issues we are seeing.
=> Switching to nuget 5.3.1

src/NuGet.Services.Logging/ApplicationInsights.cs, src/NuGet.Services.Logging/ApplicationInsightsConfiguration.cs, src/NuGet.Services.Logging/NuGet.Services.Logging.csproj, tests/NuGet.Services.Logging.Tests/ApplicationInsightsTests.cs, tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj
Verified changes locally against the solution that reproduced the AppInsights bug, and this work-around works.
Also need to verify our usage of `TelemetryConfiguration.Active` throughout the code consuming this library, as that API is being deprecated, and `TelemetryConfiguration.Active` won't pick up this custom initialized instance.
=> Work-around heartbeat interval initialization bug in AI

src/NuGet.Services.Logging/ApplicationInsightsConfiguration.cs
See https://github.com/NuGet/NuGet.Jobs/pull/837#discussion_r353380789
=> Make ApplicationInsightsConfiguration implement IDisposable

src/NuGet.Services.Logging/LoggingSetup.cs, src/NuGet.Services.Logging/TelemetryClientWrapper.cs
The `LoggingSetup` should no longer use the `TelemetryConfiguration.Active` static, and must support providing an already configured `TelemetryConfiguration` instance again.
Even though this method call is marked `[Obsolete]` for this SeriLog sink, there's currently no other way to pass in the active `TelemetryConfiguration` as configured in DI.
These SeriLog APIs are very likely to change again to support passing in the `TelemetryConfiguration` somehow, in light of `TelemetryConfiguration.Active` being deprecated by AI.
See also https://github.com/serilog/serilog-sinks-applicationinsights/issues/121.
=> Support already configured TelemetryConfiguration for LoggingSetup

src/NuGet.Services.Logging/TelemetryInitializers/MachineNameTelemetryInitializer.cs
This type belongs in `NuGet.Services.Logging` as it can be generally reused and is not specific to `Owin`.
In addition, there's no need to retrieve the machine name from `Environment.MachineName` on every telemetry initialization, which may happen multiple times for the same telemetry item.
=> Port MachineNameTelemetryInitializer from NuGet.ApplicationInsights.Owin

src/NuGet.Services.Logging/NuGet.Services.Logging.csproj, src/NuGet.Services.Logging/TelemetryInitializers/AzureWebAppTelemetryInitializer.cs, tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj, tests/NuGet.Services.Logging.Tests/TelemetryInitializers/AzureWebAppTelemetryInitializerFacts.cs
Ported [`AzureWebAppTelemetryInitializer`](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.SearchService/App_Start/AzureWebAppTelemetryInitializer.cs) from NuGet.Services.Metadata
=> Port AzureWebAppTelemetryInitializer

src/NuGet.Services.AzureManagement/NuGet.Services.AzureManagement.csproj, src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj, src/NuGet.Services.Owin/NuGet.Services.Owin.csproj, src/NuGet.Services.Sql/AzureSqlConnectionStringBuilder.cs, src/NuGet.Services.Sql/NuGet.Services.Sql.csproj, tests/NuGet.Services.Owin.Tests/NuGet.Services.Owin.Tests.csproj
Updating the Owin and Identity Model packages as part of the SameSite cookie mitigation work going into the NuGetGallery.
NuGet.Services.Sql needs an update to the AAD authority template as the authority resolution changed as described at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1346
=> Update Owin/IdentityModel packages

src/NuGet.Services.Configuration/ConfigurationRootSecretReaderFactory.cs, src/NuGet.Services.Configuration/Constants.cs, src/NuGet.Services.KeyVault/CertificateUtility.cs, src/NuGet.Services.KeyVault/KeyVaultConfiguration.cs, src/NuGet.Services.KeyVault/KeyVaultReader.cs, src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj, tests/NuGet.Services.Configuration.Tests/ConfigurationRootSecretReaderFactoryFacts.cs, tests/NuGet.Services.Configuration.Tests/NuGet.Services.Configuration.Tests.csproj
This is needed to be consumed in the code and in to be used in Jobs.Common
=> Update KeyVault to use Managed Identities

src/NuGet.Services.KeyVault/CachingSecretReader.cs, src/NuGet.Services.KeyVault/EmptySecretReader.cs, src/NuGet.Services.KeyVault/ISecretInjector.cs, src/NuGet.Services.KeyVault/ISecretReader.cs, src/NuGet.Services.KeyVault/KeyVaultReader.cs, src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj, src/NuGet.Services.KeyVault/RefreshableSecretReader.cs, src/NuGet.Services.KeyVault/SecretInjector.cs, src/NuGet.Services.Sql/AzureSqlConnectionFactory.cs, tests/NuGet.Services.KeyVault.Tests/CachingSecretReaderFacts.cs, tests/NuGet.Services.KeyVault.Tests/KeyVaultReaderFormatterFacts.cs, tests/NuGet.Services.Sql.Tests/AzureSqlConnectionFactoryFacts.cs, tests/NuGet.Services.Sql.Tests/MockFactory.cs
Currently we don't have the logs around the caching control of secret reader.
In order to understand the on-line behavior of certificates (SQL), try to populate the logger to the corresponding parts.
=> [ECR] Populate logger to have better telemetry

src/NuGet.Services.Configuration/NuGet.Services.Configuration.csproj, src/NuGet.Services.Configuration/StringArrayConverter.cs, tests/NuGet.Services.Configuration.Tests/NuGet.Services.Configuration.Tests.csproj, tests/NuGet.Services.Configuration.Tests/StringArrayConverterFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/3020
We have some internal configuration that we want to pull into the private build of gallery that has an array configuration variable. The way we do configuration in gallery is via `TypeConverter`/component model stuff and our config comes from string to string pairs. Therefore if the configuration model has a string array in it, this is how we handle it.
Note that we already have the implementation here in gallery:
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery.Services/Helpers/StringArrayConverter.cs
However I'd like to move it to a common place so that an internal project that gallery will depend on with build magic can use it too.
=> Add StringArrayConverter to handle string arrays in Gallery-style config

src/NuGet.Services.Configuration/SecretDictionary.cs, tests/NuGet.Services.Configuration.Tests/SecretDictionaryFacts.cs
NgJobs use the "SecretDictionary" to inject the connection string from the arguments. We should not inject the connection string until we pass it to the SQL connection factory like other fixes.
Update the "SecretDictionary" not to inject the connection string.
=> [ECR-SQL] Update "SecretDictionary" not to inject the connection string for NgJobs. 

src/NuGet.Services.KeyVault/CachingSecretReader.cs
It's better if we can log the time cost which includes refreshing the caching.
=> Log the time after refreshing secret caching

build/common.ps1, src/NuGet.Services.AzureManagement/NuGet.Services.AzureManagement.csproj, tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj
We should not using the System.Text.RegularExpressions 4.3.0 package.
Remove a problematic template from our .NET CLI installation. This is the easiest way for us to work-around the issue. I have filed a but against the template owners but we should not be blocked on this.
=> Remove unnecessary dependencies to fix Component Governance

build.ps1, build/common.ps1, src/NuGet.Services.AzureManagement/NuGet.Services.AzureManagement.csproj, src/NuGet.Services.FeatureFlags/NuGet.Services.FeatureFlags.csproj, src/NuGet.Services.Incidents/NuGet.Services.Incidents.csproj, src/NuGet.Services.Messaging.Email/NuGet.Services.Messaging.Email.csproj, src/NuGet.Services.Messaging/NuGet.Services.Messaging.csproj, src/NuGet.Services.Status.Table/NuGet.Services.Status.Table.csproj, src/NuGet.Services.Status/NuGet.Services.Status.csproj
This is to reduce binding redirect pain. We take a similar approach on our other common packages.
I also stopped making .symbols.nupkg for our packages. AFAIK none of us have ever used them. It increases build time, artifact sizes, and signing times. If anyone has objections, I can add it back in.
=> Set assembly version to 2.0.0.0 for all builds

build/common.ps1
Job packages are not really dependency packages per se. They are the shape that Octopus wants.
This significantly reduces CI log noise.
=> Add default NoWarn to nuget.exe package since this is used for job packages

build.ps1
We cannot easily use 2.0.0.0 since MSBuild rejects binding to a lower assembly version (2.72.0.0 -> 2.0.0.0), even when I added a binding redirect, which is weird.
=> Bump assembly version up to 3.0.0.0

src/NuGet.Services.Logging/NuGet.Services.Logging.csproj, src/NuGet.Services.Logging/TelemetryInitializers/KnownOperationNameEnricher.cs, tests/NuGet.Services.Logging.Tests/NuGet.Services.Logging.Tests.csproj, tests/NuGet.Services.Logging.Tests/TelemetryInitializers/KnownOperationNameEnricherFacts.cs
This is moved from [NuGetGallery](https://github.com/NuGet/NuGetGallery/blob/2aaa5ce7f9be3b59ba2abff7f8295e4153d1e828/src/NuGetGallery/Telemetry/KnownOperationNameEnricher.cs) and made more general purpose.
This will be used in the search service.
=> Move KnownOperationNameEnricher to a common place

src/NuGet.Services.Contracts/ServiceBus/IBrokeredMessage.cs, src/NuGet.Services.ServiceBus/BrokeredMessageWrapper.cs
The brokered message `string GetBody()` method expects that the message was serialized with  `System.Runtime.Serialization.DataContractSerializer` with a binary `System.Xml.XmlDictionaryReader`. This does not work for secret expiration, since the azure event grid puts message into the subscription and not necessarily with the same serializer contract. It makes sense to provide a way to stream the message from BrokeredMessage directly into bytes and the client can decide to deserialize it as required.
=> Add stream support for service bus BrokeredMessage

src/NuGet.Services.Contracts/Logging/ITelemetryClient.cs, src/NuGet.Services.Logging/TelemetryClientWrapper.cs
Application Insights SDK buffers telemetry for up to 30 seconds (see [this](https://devblogs.microsoft.com/premier-developer/application-insights-use-case-for-telemetryclient-flush-calls/)). In https://github.com/NuGet/Engineering/issues/3270, I updated the symbol ingester job to forcefully restart if the job reached a non-recoverable state. Today, the job doesn't flush upon restarting, which causes up to 30 seconds of telemetry to be lost.
=> Allow jobs and services to flush telemetry 

src/NuGet.Services.Validation/CheckValidationSetData.cs, src/NuGet.Services.Validation/CheckValidatorData.cs, src/NuGet.Services.Validation/PackageValidationMessageData.cs, src/NuGet.Services.Validation/PackageValidationMessageType.cs, src/NuGet.Services.Validation/ProcessValidationSetData.cs, src/NuGet.Services.Validation/ServiceBusMessageSerializer.cs, src/NuGet.Services.Validation/StartValidationData.cs, src/NuGet.Services.Validation/ValidatingType.cs, tests/NuGet.Services.Validation.Tests/ServiceBusMessageSerializerTests.cs, tests/NuGet.Services.Validation.Tests/TestData.Designer.cs, tests/NuGet.Services.Validation.Tests/TestData.resx
Create the libraries to serialize and deserialize the new [`StartValidation`](https://github.com/NuGet/Engineering/blob/master/Server.Specs/ValidationProtocol.md#start-validation-message) and [`CheckValidationSet`](https://github.com/NuGet/Engineering/blob/master/Server.Specs/OrchestratorUnifiedValidations.md#checkvalidationset) messages.
Part of https://github.com/NuGet/Engineering/issues/3612
<details>
<summary>Testing...</summary>
Build: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4406068&view=results
</details>
/cc @nikhgup
=> Update Orchestrator message serialization libraries

NuGet.Server.Common.sln, build.ps1, src/NuGet.Services.Testing.Entities/IDbSetMockExtensions.cs, src/NuGet.Services.Testing.Entities/IValidationEntitiesContextExtensions.cs, src/NuGet.Services.Testing.Entities/NuGet.Services.Testing.Entities.csproj, src/NuGet.Services.Testing.Entities/README.md, src/NuGet.Services.Testing.Entities/TestDbAsyncQueryProvider.cs
NuGet.Jobs facilitates unit testing Entity Framework context in [`Validation.PackageSigning.Helpers`](https://github.com/NuGet/NuGet.Jobs/tree/262da48ed05d0366613bbf1c54f47879aad96dcd/tests/Validation.PackageSigning.Helpers). This change moves these helpers into a new project, `NuGet.Services.Testing.Entities`, so that we can share them across other repositories like NuGetMonitoring and NuGetGallery.
See: https://github.com/NuGet/NuGet.Jobs/pull/960
See: https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetMonitoring/pullrequest/1668
Part of: https://github.com/NuGet/Engineering/issues/3584
Test release: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4446773&view=results
=> Add shared project to unit test Entity Framework

src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj, src/NuGet.Services.ServiceBus/TopicClientWrapper.cs, tests/NuGet.Services.ServiceBus.Tests/NuGet.Services.ServiceBus.Tests.csproj
Adding support for client secret based authentication
upgrading servicebus library
adding Microsoft.Identity.client nuet package
Tracked by: https://github.com/NuGet/Engineering/issues/3650
=> Add client secret authentication for Service Bus

src/NuGet.Services.Contracts/ServiceBus/ITopicClient.cs, src/NuGet.Services.ServiceBus/TopicClientWrapper.cs
Marketplace job agents are synchronous. Adding async support would be a large undertaking, so instead, we will use synchronous methods to send Service Bus messages.
=> adding sync methods for servicebus to be used for marketplace

build/common.ps1
Sometimes you need it, and making msbuild to produce binlog in local copy is a bit of a pain.
This adds appropriate arguments to all cmdlets that end up calling msbuild.
=> Adding build cmdlet arguments to make msbuild produce binlog

src/NuGet.Services.FeatureFlags/FeatureFlagCacheService.cs, tests/NuGet.Services.FeatureFlags.Tests/FeatureFlagCacheServiceFacts.cs
Progress on https://github.com/NuGet/Engineering/issues/3522
`FeatureFlagCacheService` needs to be a singleton in services to maintain cache, but it should not be holding on to an instance of a storage service: it prevents proper secret refresh. The class is modified instead to receive a storage service factory that it uses to produce instances of a storage service as needed.
=> Storage factory in FeatureFlagCacheService

src/NuGet.Services.Configuration/ConfigurationBuilderExtensions.cs, src/NuGet.Services.Configuration/KeyVaultJsonInjectingConfigurationSource.cs
This will allow environments that expect config to come from environment variables (e.g. App Service app settings) to use the same code as local environments that more easily use JSON config files.
=> Allow optional JSON config files

build/init.ps1
- init.ps1 was updated to clone a repository instead of using the GitHub content Api. This will allow us to avoid throttle issues.
- Basically it clones the ServerCommon repository and moves the needed files on their respective directories.
- I dropped the usage of the specific commit we were using, I thought it would be better to have only the branch name and the commit used in the script will be the latest on that branch, this will allow us to better test a certain branch when we make changes to ServerCommon scripts.
=> Update init.ps1 to clone repository instead of using GH APIs.

build/init.ps1
This change will help us to maintain a commit hash for specific reference when building a project.
- Since we cannot clone a repository using only a commit id, I'm adding branch name to help us have the flexibility to specify our own if necessary on `$BuildBranch` (default is `main`).
- `$BuildBranchCommit` specifies the exact commit the branch will move to. If no commit is specified, then it will use the latest from the cloned branch.
=> init.ps1 script now clones ServerCommon repository with a specific commit.

build/common.ps1
Remove .editorconfig for builds because the precedence rule for conflicting severity entries from a ruleset file (SDL) and an EditorConfig is undefined.
_Update default commit of Private Build before checking in_
=> [Roslyn Analyzer - 3] Remove .editorconfig to use the compliant ruleset for builds.

build/common.ps1
Previously used version of .net core installer does not seem to be available anymore (and causes build failures). 3.1 is LTS, so will use that one instead.
=> .net core 2.2 is out of support, trying to use 3.1

src/NuGet.Services.Messaging.Email/NuGet.Services.Messaging.Email.csproj
Upgrade markdig to 0.26.0
Test: 
Functional test + unit test
Also manually tested email publisher, detail page with readme package
=> update markdig version

src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj, tests/NuGet.Services.ServiceBus.Tests/NuGet.Services.ServiceBus.Tests.csproj
`WindowsAzure.ServiceBus` takes a dependency on the `System.IdentityModel.Tokens.Jwt` which is overridden by another package with a superior version of `Jwt` library which breaks the managed identity authentication due to a breaking change. Updating the service bus to up the underlying dependency.
=> Update service bus version to update the breaking dependencies

src/NuGet.Services.Storage/AggregateStorage.cs, src/NuGet.Services.Storage/AzureStorage.cs, src/NuGet.Services.Storage/AzureStorageFactory.cs, src/NuGet.Services.Storage/CloudBlobStorageExtensions.cs, src/NuGet.Services.Storage/FileStorage.cs, src/NuGet.Services.Storage/IStorage.cs, src/NuGet.Services.Storage/NuGet.Services.Storage.csproj, src/NuGet.Services.Storage/Storage.cs, src/NuGet.Services.Storage/StorageConstants.cs, src/NuGet.Services.Storage/StorageListItem.cs, tests/NuGet.Services.Storage.Tests/AzureStorageFacts.cs
Porting blob copy routines from https://github.com/NuGet/NuGet.Jobs/blob/main/src/Catalog/Persistence/
Added the ability to request blob metadata when listing blobs and a function to update it.
Moved some particularly noisy logs under `Verbose` flag.
=> Blob copy routines

src/NuGet.Services.Storage/AzureStorage.cs
`Properties` property is actually defined in `CloudBlob` which is a parent of `CloudBlockBlob`. Using a proper superclass allows to support many blob types, not only block blobs.
Fails with append blobs before change, succeeds after.
=> Wider applicability of getting blob last modified time.

src/NuGet.Services.Messaging.Email/NuGet.Services.Messaging.Email.csproj, src/NuGet.Services.Messaging/NuGet.Services.Messaging.csproj
First step in addressing: https://github.com/NuGet/Engineering/issues/4434
This reduces the [ATF footprint](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701) in building `NuGetGallery.Services` `net6` targets. Targeting `net6` in these libraries is generally sufficient to not deploy framework binaries in their nupkgs, however some are still included (e.g. MarkdownMailer) but are not problematic for this targeting work.
=> Add net6 target to messaging projects

src/NuGet.Services.Contracts/NuGet.Services.Contracts.csproj, src/NuGet.Services.Messaging.Email/NuGet.Services.Messaging.Email.csproj, src/NuGet.Services.Messaging/NuGet.Services.Messaging.csproj
Partially addresses: https://github.com/NuGet/Engineering/issues/4434
This transitive dependency on MarkdownMailer was causing errors in CI as it was using attempting [ATF]((https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701) and failing. We don't need this dependency for this work, and possibly a substitute dependency could be included in a netcore target if mailing with markdown were needed in that context, but this would be separate work.
Note also that a `net6` target is inconsistent with other existing netcore targets in our repos, and I want to bring it back into alignment by retrgeting to `netstandard2.1` which is compatible with `net6`. When we do wish to migrate all of these targets to `net6`, this should be separate work which would include necessary …
=> Excise MarkdownMail from netcore target in NuGet.Services.Messaging.Email

build/common.ps1, build/runcodeanalysis.ps1
Suppressed warning about commit hash mistaken for a secret.
Removed PS code enabling TLS 1.2. It seems it is enabled on our build machines by default now.
=> DevSkim warnings addressed.

build/common.ps1
We switched to building our projects using MS-hosted agents that have dotnet preinstalled with an assortment of SDKs. There is no need for us download and install one every time we build something, we can reuse existing one just fine.
=> Preferring build environment's dotnet.exe to our own.

build/common.ps1
At build time we occasionally need to add private package sources to NuGet.Config. Added function to do that.
The function will create package source if it is absent in the file.
=> Function for adding new package source mappings to nuget.config files.

src/NuGet.Services.KeyVault/NuGet.Services.KeyVault.csproj, src/NuGet.Services.ServiceBus/NuGet.Services.ServiceBus.csproj
Update azure identity to 1.10.4
PMP has dependency on ServerCommon, update this package. 
Address: https://devdiv.visualstudio.com/OnlineServices/_git/PackageManagement-Platform/pullrequest/526886
=> Update azure identity to 1.10.4

src/NuGet.Services.Contracts/ServiceBus/IReceivedBrokeredMessage.cs, src/NuGet.Services.ServiceBus/ServiceBusReceivedMessageWrapper.cs
One of the monitoring jobs requires access to raw message body data to properly deserialize the message. Calling `BrokeredMessage.GetBody<Stream>` worked with the previous version of the Service Bus library. Migrating to new version broke that (as there is no direct equivalent and our reimplementation disregarded that case). Adding explicit method to support that scenario.
Another potential solution here is to update `GetBody<TStream>` implementation to check if `TStream` is `System.IO.Stream` and do something else, but I'm not sure what else it might break. Creating new method is safer.
=> `GetRawBody` method

.pipelines/Release-trigger.yml
This pipeline shouldn't be triggered on PRs. Disabling.
Same was done in other repos: https://github.com/NuGet/NuGet.Jobs/pull/1201, https://github.com/NuGet/NuGetGallery/pull/9930
=> Disabling PR triggering

src/NuGet.Services.Configuration/ConfigurationRootSecretReaderFactory.cs, src/NuGet.Services.Configuration/Constants.cs, src/NuGet.Services.KeyVault/KeyVaultConfiguration.cs
* Added "ManagedIdentityClientId" configuration, so that we can add only one MSI on config files for all services in a job, KV/Storage/etc.
* KeyVault configuration now uses "KeyVault_ClientId" if specified or fallbacks to "ManagedIdentityClientId".
=> Add global MSI client id for KV

.pipelines/ServerCommon-CI.yml, Directory.Packages.props, NuGet.config, build.ps1, build/common.ps1, test.ps1, tests/NuGet.Services.Logging.Tests/App.config, tools/AzureSqlConnectionTest/App.config
This is further clean up to ease a repository merge. 
Summary of changes:
- Switch publish test results to `VSTest` since `dotnet test` is used.
- Align package versions with NuGetGallery and NuGet.Jobs
- Simplify package source mapping to match NuGetGallery and NuGet.Jobs
- Remove build.ps1 `-CleanCache`. It's not used anywhere and is weak due to only clearing `temp` and `http-cache`
- Remove useless `app.config` files
=> Align package versions, remove unused method, quality "common" build steps

src/NuGet.Services.Status.Table/ChildEntity.cs, src/NuGet.Services.Status.Table/ComponentAffectingEntity.cs, src/NuGet.Services.Status.Table/CursorEntity.cs, src/NuGet.Services.Status.Table/Manual/ManualStatusChangeEntity.cs
Currently, `ChildEntity` does not set PK and RK. This causes `StatusAggregator` tests in NuGetGallery to fail.
This supports a repository merge effort.
Also, remove internal `TableEntity` field in other entities since it adds no value. It takes this PR comment all the way:
https://github.com/NuGet/ServerCommon/pull/430#discussion_r1671439519
=> Fix Partition Key and Row Key assignments in Status entities

Directory.Packages.props, src/NuGet.Services.Storage/AzureStorage.cs, src/NuGet.Services.Storage/AzureStorageFactory.cs, src/NuGet.Services.Storage/IStorage.cs, src/NuGet.Services.Storage/NuGet.Services.Storage.csproj, tests/NuGet.Services.Storage.Tests/AzureStorageNewFacts.cs
The only place that uses this method is here:
https://github.com/NuGet/NuGetGallery/blob/99b2b4961bc4d62e9bab60993390b08260be639a/src/Stats.PostProcessReports/DetailedReportPostProcessor.cs#L208
This uses server-side copy already. So the extra dependency on `DataMovement` is not needed.
This PR essentially copies the copy implementation from the original copy of this copied project, still existing here:
https://github.com/NuGet/NuGetGallery/blob/99b2b4961bc4d62e9bab60993390b08260be639a/src/Catalog/Persistence/AzureStorage.cs#L221-L274
Also add a helper method to replicate this:
https://github.com/NuGet/NuGetGallery/blob/2e4a1498efac7feb99ce49a71b0bf13863448fad/src/NuGetGallery.Core/Services/CloudBlobClientWrapper.cs#L45-L46
=> Change Azure Storage copy to use server side copy

src/NuGet.Services.Storage/AzureStorage.cs, src/NuGet.Services.Storage/AzureStorageFactory.cs, tests/NuGet.Services.Storage.Tests/AzureStorageNewFacts.cs
Before moving to the new Azure SDK, `AzureStorage` was tolerant of existing containers having a different public access level:
https://github.com/NuGet/ServerCommon/blob/f6781f41bb6ec921b8fe81cc05882fe0af7897f6/src/NuGet.Services.Storage/AzureStorage.cs#L53-L55
Because of this, the actual public blob access level on some containers (such as the one used for the Gallery.CredentialExpiration job) have drifted from Blob public access (i.e. becoming no public access). Because of the previous implementation, this was allowsed. `CreateIfNotExists` would return false because the container already existed and updating the public access level would not happen. With the current implementation based on the new SDK, the code tries to update the public access level every time. This fails when the …
=> Force AzureStorageFactory to specify blob public access
